version: '3.8'

services:
  webhook:
    build: .
    image: techiescamp/kubeimageguard:latest
    container_name: kubeimageguard
    ports:
      - "5000:5000"
    environment:
      - SESSION_SECRET=change_this_in_production
    restart: unless-stopped