apiVersion: v1
kind: Config
# clusters refers to the webhook service
clusters:
- name: dockerhub-image-policy-webhook
  cluster:
    certificate-authority: /etc/kubernetes/pki/admission-webhook-ca.crt
    server: https://dockerhub-image-policy-webhook.image-policy-system.svc:443/webhook

users:
- name: api-server
  user:
    client-certificate: /etc/kubernetes/pki/apiserver-client.crt
    client-key: /etc/kubernetes/pki/apiserver-client.key

current-context: webhook
contexts:
- context:
    cluster: dockerhub-image-policy-webhook
    user: api-server
  name: webhook